import { StyleSheet, Platform } from 'react-native';
import { AppColors } from '../../theme/theme';

export default function createStyles(ms, mvs, fs) {
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: AppColors.background },
    horizontalPadd:{
      paddingHorizontal:ms(15)
    },
    headerWrap: {
      backgroundColor: AppColors.primary,
      paddingBottom: mvs(18), 
    },
    headerTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: ms(16),
      paddingTop: mvs(6),
    },
    headerTopLeft: { flexDirection: 'row', alignItems: 'center', flexShrink: 1 },
    backBtn: {
      width: ms(30),
      height: ms(30),
      borderRadius: ms(15),
      backgroundColor: 'rgba(255,255,255,0.20)',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: ms(10),
    },
    orderIdText: { color: AppColors.onPrimary, fontSize: fs(15.5), fontWeight: '700' },
    headerTopRight: { flexDirection: 'row', alignItems: 'center' },
    severityPill: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: ms(10),
      paddingVertical: mvs(5),
      borderRadius: ms(12),
      marginRight: ms(8),
    },
    severityPillText: { fontSize: fs(11.5), fontWeight: '700', marginLeft: ms(4) },
    dotsBtn: { width: ms(30), height: ms(30), alignItems: 'center', justifyContent: 'center' },

    titleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: mvs(14),
      marginHorizontal: ms(16),
      flexWrap: 'wrap',
    },
    screenTitle: { color: AppColors.onPrimary, fontSize: fs(18), fontWeight: '800' },
    lineBadge: {
      marginLeft: ms(10),
      paddingHorizontal: ms(10),
      paddingVertical: mvs(3),
      borderRadius: ms(10),
      backgroundColor: 'rgba(255,255,255,0.22)',
    },
    lineBadgeText: { color: AppColors.onPrimary, fontSize: fs(11.5), fontWeight: '700' },

    progressRow: { flexDirection: 'row', marginHorizontal: ms(16), marginTop: mvs(10), gap: ms(6),width:ms(80) },
    progressSeg: { flex: 1, height: mvs(3), borderRadius: ms(2), backgroundColor: 'rgba(255,255,255,0.28)' },
    progressSegActive: { backgroundColor: AppColors.onPrimary },

    summaryWrap: { marginTop: mvs(14), marginHorizontal: ms(16) },
    summaryRow: { flexDirection: 'row', alignItems: 'center', marginBottom: mvs(6) },
    summaryText: { color: 'rgba(255,255,255,0.92)', fontSize: fs(13.5), fontWeight: '400', marginLeft: ms(8), flexShrink: 1 },

    viewAllPill: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      marginTop: mvs(6),
      marginHorizontal: ms(16),
      backgroundColor: 'rgba(255,255,255,0.18)',
      paddingHorizontal: ms(12),
      paddingVertical: mvs(6),
      borderRadius: ms(16),
    },
    viewAllText: { color: AppColors.onPrimary, fontSize: fs(12.5), fontWeight: '700', marginRight: ms(4) },

    body: { flex: 1 },
    scrollContent: { paddingHorizontal: ms(16), paddingTop: mvs(16), paddingBottom: mvs(24) },

    sectionCard: {
      backgroundColor: AppColors.surface,
      borderRadius: ms(16),
      overflow: 'hidden',
      marginBottom: mvs(16),
      shadowColor: '#000',
      shadowOpacity: 0.05,
      shadowRadius: ms(8),
      shadowOffset: { width: 0, height: mvs(3) },
      elevation: 2,
    },
    sectionHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: AppColors.primaryLight ?? '#E6F6F5',
      paddingVertical: mvs(11),
      paddingHorizontal: ms(14),
    },
    sectionHeaderText: { color: AppColors.shadowClr ?? AppColors.primary, fontSize: fs(13.5), fontWeight: '600', marginLeft: ms(8) },
    sectionBody: { paddingHorizontal: ms(14), paddingVertical: mvs(6) },

    detailRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: mvs(10),
    },
    detailRowMultiline: {
      flexDirection: 'column',
      alignItems: 'flex-start',
      paddingVertical: mvs(10),
    },
    detailValueMultiline: {
      color: AppColors.textPrimary,
      fontSize: fs(14.5),
      fontWeight: '600',
      textAlign: 'left',
      marginTop: mvs(6),
      lineHeight: fs(20),
      width: '100%',
    },
    detailRowBorder: { borderTopWidth: 1, borderTopColor: '#EEF2F2' },
    detailLabel: { color: AppColors.textSecondary, fontSize: fs(14), flexShrink: 0, paddingRight: ms(10) },
    detailValue: { color: AppColors.textPrimary, fontSize: fs(14.5), fontWeight: '500', textAlign: 'right', flexShrink: 1,flex: 1 },
    detailValueItalic: { fontStyle: 'italic', fontWeight: '500', color: AppColors.textPrimary },
    liveDot: { width: ms(7), height: ms(7), borderRadius: ms(3.5), backgroundColor: AppColors.error, marginRight: ms(5) },
    liveValueRow: { flexDirection: 'row', alignItems: 'center' },
    liveValueText: { color: AppColors.error, fontSize: fs(14.5), fontWeight: '500' },

    /* ── CAP selector / chosen list (CAP Information screen) ── */
    capDashedBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderStyle: 'dashed',
      borderColor: AppColors.primary,
      borderRadius: ms(12),
      paddingVertical: mvs(14),
      marginHorizontal: ms(14),
      marginVertical: mvs(12),
    },
    capDashedBtnText: { color: AppColors.primary, fontSize: fs(14.5), fontWeight: '700', marginLeft: ms(6) },
    capChosenRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: '#F7F9F9',
      borderRadius: ms(12),
      paddingHorizontal: ms(14),
      paddingVertical: mvs(12),
      marginHorizontal: ms(14),
      marginBottom: mvs(10),
    },
    capChosenText: { color: AppColors.textPrimary, fontSize: fs(14), fontWeight: '600', flex: 1, paddingRight: ms(10) },

    // Horizontal padding now derives from ms() instead of a one-time
    // Dimensions.get('window') read at module load, so it stays correct
    // across rotation, split-view resizing, and tablet widths.
    footer: {
      backgroundColor: AppColors.surface,
      paddingHorizontal: ms(16),
      paddingTop: mvs(14),
      paddingBottom: Platform.OS === 'ios' ? mvs(26) : mvs(20),
      borderTopWidth: 1,
      borderTopColor: '#E8EDED',
      ...Platform.select({
        ios: { shadowColor: '#000', shadowOffset: { width: 0, height: -2 }, shadowOpacity: 0.05, shadowRadius: 6 },
        android: { elevation: 6 },
      }),
    },
    primaryBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: AppColors.primary,
      paddingVertical: mvs(14),
      borderRadius: ms(20),
      gap: ms(8),
    },
    primaryBtnDisabled: { backgroundColor: '#D7DEDE' },
    primaryBtnText: { color: AppColors.onPrimary, fontSize: fs(16), fontWeight: '800' },
    primaryBtnTextDisabled: { color: '#8A9898' },
    /* ── CAP Taken row (clickable, badge + chevron) ── */
    capTakenValueWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      maxWidth: '62%',
    },
    capTakenValueText: {
      color: AppColors.textPrimary,
      fontSize: fs(14.5),
      fontWeight: '700',
      flexShrink: 1,
      textAlign: 'right',
    },
    capTakenBadge: {
      backgroundColor: AppColors.warning ?? '#F5A623',
      borderRadius: ms(9),
      paddingHorizontal: ms(6),
      paddingVertical: mvs(1),
      marginLeft: ms(6),
    },
    capTakenBadgeText: {
      color: AppColors.onPrimary,
      fontSize: fs(10.5),
      fontWeight: '800',
    },

    /* ── Full CAP-taken list modal ── */
    capTakenOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.35)',
      justifyContent: 'flex-end',
    },
    capTakenSheet: {
      backgroundColor: AppColors.surface,
      borderTopLeftRadius: ms(20),
      borderTopRightRadius: ms(20),
      paddingHorizontal: ms(16),
      paddingTop: mvs(14),
      paddingBottom: Platform.OS === 'ios' ? mvs(30) : mvs(18),
    },
    /* ── 3-dot manager-override dropdown ── */
    menuOverlay: { flex: 1, backgroundColor: 'transparent' },
    menuCard: {
      position: 'absolute',
      right: ms(16),
      top: mvs(46),
      backgroundColor: AppColors.surface,
      borderRadius: ms(14),
      paddingVertical: mvs(6),
      minWidth: ms(210),
      shadowColor: '#000',
      shadowOpacity: 0.18,
      shadowRadius: ms(14),
      shadowOffset: { width: 0, height: mvs(6) },
      elevation: 10,
    },
    menuHeaderRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: ms(14), paddingVertical: mvs(10) },
    menuHeaderText: { color: AppColors.textTertiary, fontSize: fs(11.5), fontWeight: '800', letterSpacing: 0.4, marginLeft: ms(8) },
    menuDivider: { height: 1, backgroundColor: '#EEF2F2' },
    menuItemRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: ms(14), paddingVertical: mvs(12) },
    menuItemText: { color: AppColors.error, fontSize: fs(14), fontWeight: '700', marginLeft: ms(8) },

    /* ── Close-without-CAP / Select-CAP sheet content ── */
    sheetLabelRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: mvs(6),marginTop:mvs(5) },
    sheetLabel: { color: AppColors.textPrimary, fontSize: fs(13.5), fontWeight: '700' },
    sheetCounter: { color: AppColors.textTertiary, fontSize: fs(12) },
    requiredMark: { color: AppColors.error },
    reasonInput: {
      backgroundColor: AppColors.textInverse,
      borderRadius: ms(12),
      borderWidth:ms(0.4),
      borderColor:AppColors.black,
      padding: ms(12),
      minHeight: mvs(96),
      fontSize: fs(14.5),
      color: AppColors.neutral600,
      textAlignVertical: 'top',
    },
    sheetFooterRow: { flexDirection: 'row', gap: ms(12), marginTop: mvs(18) },
    sheetCancelBtn: {
      flex: 1,
      paddingVertical: mvs(13),
      borderRadius: ms(24),
      borderWidth: 1.5,
      borderColor: '#E2E8E8',
      alignItems: 'center',
      justifyContent: 'center',
    },
    sheetCancelText: { fontSize: fs(15), fontWeight: '700', color: AppColors.textSecondary },
    sheetDangerBtn: {
      flex: 1,
      paddingVertical: mvs(13),
      borderRadius: ms(24),
      backgroundColor: AppColors.error,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sheetDangerBtnText: { fontSize: fs(15), fontWeight: '800', color: AppColors.onPrimary },

    capOptionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#F7F9F9',
      borderRadius: ms(12),
      borderWidth: 1.5,
      borderColor: 'transparent',
      paddingHorizontal: ms(14),
      paddingVertical: mvs(13),
      marginBottom: mvs(10),
    },
    capOptionRowActive: { backgroundColor: AppColors.primaryLight ?? '#E6F6F5', borderColor: AppColors.primary },
    capOptionText: { flex: 1, fontSize: fs(14.5), color: AppColors.textPrimary, fontWeight: '600' },
    capOptionTextActive: { color: AppColors.primaryDark ?? AppColors.primary },
    capRadio: { width: ms(20), height: ms(20), borderRadius: ms(10), borderWidth: 1.5, borderColor: '#C7D3D3', marginRight: ms(10) },

    customCapLabel: {
      fontSize: fs(11.5),
      fontWeight: '800',
      color: AppColors.textTertiary,
      letterSpacing: 0.4,
      marginTop: mvs(4),
      marginBottom: mvs(8),
    },
    customCapInput: {
      backgroundColor: '#F7F9F9',
      borderRadius: ms(12),
      padding: ms(12),
      fontSize: fs(14.5),
      color: AppColors.textPrimary,
      marginBottom: mvs(16),
    },
    applyBtn: {
      paddingVertical: mvs(14),
      borderRadius: ms(26),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#D7DEDE',
    },
    applyBtnActive: { backgroundColor: AppColors.primary },
    applyBtnText: { fontSize: fs(15.5), fontWeight: '800', color: '#8A9898' },
    applyBtnTextActive: { color: AppColors.onPrimary },


    capActionList: {
      paddingHorizontal: ms(14),
      paddingVertical: mvs(10),
    },
    capActionRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginBottom: mvs(10),
    },
    capActionText: {
      color: AppColors.textPrimary,
      fontSize: fs(14.5),
      fontWeight: '400',
      marginLeft: ms(8),
      flex: 1,
      flexShrink: 1,
    },

    /* ── QC Verdict (Pass / Fail toggle + status pill) ── */
    verdictWrap: {
      paddingHorizontal: ms(14),
      paddingVertical: mvs(14),
    },
    verdictRow: {
      flexDirection: 'row',
      gap: ms(12),
    },
    verdictBtn: {
      flex: 1,
      paddingVertical: mvs(12),
      borderRadius: ms(22),
      borderWidth: 1.5,
      borderColor: '#E2E8E8',
      backgroundColor: '#F7F9F9',
      alignItems: 'center',
      justifyContent: 'center',
    },
    verdictBtnText: {
      fontSize: fs(15),
      fontWeight: '800',
      color: AppColors.textSecondary,
    },
    statusUpdatedPill: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'center',
      marginTop: mvs(12),
      paddingHorizontal: ms(12),
      paddingVertical: mvs(7),
      borderRadius: ms(16),
    },
    statusUpdatedPillPass: { backgroundColor: 'rgba(22,163,74,0.10)' },
    statusUpdatedPillFail: { backgroundColor: 'rgba(220,38,38,0.08)' },
    statusUpdatedDot: {
      width: ms(7),
      height: ms(7),
      borderRadius: ms(3.5),
      marginRight: ms(6),
    },
    statusUpdatedText: {
      fontSize: fs(13),
      fontWeight: '700',
      textAlign: 'center',
      alignSelf: 'center',
    },

    /* ── Escalate Issue row ── */
    escalateCard: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: AppColors.surface,
      borderRadius: ms(16),
      paddingHorizontal: ms(14),
      paddingVertical: mvs(13),
      marginBottom: mvs(16),
      shadowColor: '#000',
      shadowOpacity: 0.05,
      shadowRadius: ms(8),
      shadowOffset: { width: 0, height: mvs(3) },
      elevation: 2,
    },
    escalateLeft: { flexDirection: 'row', alignItems: 'center' },
    escalateIconWrap: {
      width: ms(30),
      height: ms(30),
      borderRadius: ms(15),
      backgroundColor: '#F1F5F5',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: ms(10),
    },
    escalateLabel: {
      fontSize: fs(14.5),
      fontWeight: '700',
      color: AppColors.textPrimary,
    },
  });
}